# Generated by Django 3.1.7 on 2021-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app_v3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_details_v3',
            name='expense_by',
            field=models.CharField(blank=True, choices=[('1', 'Ganesan R S'), ('2', 'Lakshmi'), ('3', 'Karthik'), ('4', 'Kaviya'), ('5', 'General')], max_length=30, null=True),
        ),
    ]
