# Generated by Django 3.1.7 on 2021-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app_v3', '0002_expense_details_v3_expense_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_details_v3',
            name='amount',
            field=models.FloatField(),
        ),
    ]
