# Generated by Django 3.1.7 on 2021-04-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_cat_master_v3_expense_details_v3_sub_cat_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_details_v3',
            name='cat_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expense_app.cat_master_v3'),
        ),
        migrations.AlterField(
            model_name='expense_details_v3',
            name='sub_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expense_app.sub_cat_v3'),
        ),
        migrations.AlterField(
            model_name='sub_cat_v3',
            name='cat_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_app.cat_master_v3'),
        ),
    ]
